// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6-8-fTl24WXVDcGUP7YrKyY4WpM7qs00',
    appId: '1:1066947496564:web:70588c4e2c1606871c5f21',
    messagingSenderId: '1066947496564',
    projectId: 'covax-7d6f2',
    authDomain: 'covax-7d6f2.firebaseapp.com',
    databaseURL: 'https://covax-7d6f2-default-rtdb.firebaseio.com',
    storageBucket: 'covax-7d6f2.appspot.com',
    measurementId: 'G-C5NB3CGF3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgdXXHzHHxOZNa1Jy0L7UzXdK5O7KKbAE',
    appId: '1:1066947496564:android:b4b69cdad7eaff3c1c5f21',
    messagingSenderId: '1066947496564',
    projectId: 'covax-7d6f2',
    databaseURL: 'https://covax-7d6f2-default-rtdb.firebaseio.com',
    storageBucket: 'covax-7d6f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3XilIWVZLBHaEzMgGI78dK9SQbKAZo7M',
    appId: '1:1066947496564:ios:60b44272676b302e1c5f21',
    messagingSenderId: '1066947496564',
    projectId: 'covax-7d6f2',
    databaseURL: 'https://covax-7d6f2-default-rtdb.firebaseio.com',
    storageBucket: 'covax-7d6f2.appspot.com',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3XilIWVZLBHaEzMgGI78dK9SQbKAZo7M',
    appId: '1:1066947496564:ios:60b44272676b302e1c5f21',
    messagingSenderId: '1066947496564',
    projectId: 'covax-7d6f2',
    databaseURL: 'https://covax-7d6f2-default-rtdb.firebaseio.com',
    storageBucket: 'covax-7d6f2.appspot.com',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6-8-fTl24WXVDcGUP7YrKyY4WpM7qs00',
    appId: '1:1066947496564:web:0adb7ffab76469c11c5f21',
    messagingSenderId: '1066947496564',
    projectId: 'covax-7d6f2',
    authDomain: 'covax-7d6f2.firebaseapp.com',
    databaseURL: 'https://covax-7d6f2-default-rtdb.firebaseio.com',
    storageBucket: 'covax-7d6f2.appspot.com',
    measurementId: 'G-NJK4TJQRV0',
  );
}
